#!/usr/bin/bash

#HOMOZYGOSITY_MAPS_CONSANG=`ls /homes/homedirs34/sghms/student/users/p1806425/test_MO43_MO65_CNV/Homozygosity_Mapper/ED_csv_bed_hm/*_analysis.bed`
#ED_CNV_CALLS=`/homes/athosnew/Genetics_Centre_Bioinformatics/CNV_calling_zahra/test_samples/test_extra_samples_BEDtools/*_BEDtoolsoverlaps_known_genes.csv`

mySamples="MO46 MO47 MO49 MO55 MO58 MO51 MO52"

for sample in $mySamples; do

	cat header.txt > ${sample}_hm_overlap_exomedepth_calls_known_genes.csv

	/homes/athosnew/Genetics_Centre_Bioinformatics/resourses/bedtools2/bin/intersectBed -a ${sample}_HM_analysis.bed -b ${sample}__sorted_unique_recalibrated.csv.bed_BEDtoolsoverlaps_known_genes.bed -wa -wb >> ${sample}_hm_overlap_exomedepth_calls_known_genes.csv

	perl -p -i -e 's/\t/,/g' ${sample}_hm_overlap_exomedepth_calls_known_genes.csv
	
done
